title: Moja Jekyll stránka
description: Stránka generovaná pomocou Jekyll a GitHub Pages
baseurl: ""  # Ak je stránka v podsložke, napr. /mojprojekt, nastav ju sem
url: "https://pdfix-documentation.github.io"

# Použitie témy (napr. minima)
theme: minima

# Inklúzia bočného panela
include:
  - _includes/sidebar.html

# Nastavenie navigácie
nav:
  - title: Domov
    url: /
  - title: O nás
    url: /about
  - title: Kontakt
    url: /contact

# Plugins (ak sú potrebné)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
